version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    restart: always

volumes:
  mongodata:
