version: "3"

services:
  frontend:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./frontend/:/app
    command: /bin/sh -c "npm install && npm run build"
    stdin_open: true # This is need for react-scripts to working inside docker

  backend:
    image: node:alpine
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    working_dir: /app
    volumes:
      - ./backend/:/app
    command: /bin/sh -c "npm install && npm start"

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
